[build]
publish = "dist/client/"
command = "npm run build"

[functions]
directory = "functions/"

[[redirects]]
from = "/*"
to = "/.netlify/functions/index"
status = 200

[[redirects]]
from = "https://payments.saturn.tech/*"
to = "https://payouts.saturn.tech/*"
status = 301

[[redirects]]
from = "https://payments.strn.network/*"
to = "https://payouts.saturn.tech/*"
status = 301